### PR TITLE
Refactor/Icons refactoring

### PR DESCRIPTION
**Pull request by SepidehShahbazi**
Completed the refactoring of documentPage icons for issue #50.

### CODE REVIEW

**Review by mahid797 — APPROVED** [review]
Assuming you have tested each icon, I am approving these changes. But I will not merge the PR, so you can keep working on the same branch.

**Comment by gorkem-bwl** [comment]
@SepidehShahbazi once you have a PR with a visual change, could you send images/videos supporting your work? This will also help me understand what has changed overall. Thanks!

**Comment by parwatcodes** [comment]
> @SepidehShahbazi once you have a PR with a visual change, could you send images/videos supporting your work? This will also help me understand what has changed overall. Thanks!

Also, If possible it's better to create the PR with UI changes for better readability, It would let reviewers know about the exact changes in UI.

## UI Changes Overview

### Before
Previous UI

### After
Updated UI

---

## Summary of Changes
- Updated button styles.
- Improved form layout.
- Fixed responsive issues on mobile.

**Comment by mahid797** [comment]
@gorkem-bwl @parwatcodes 

There are no UI changes in this PR as this is just a refactoring of the icons.

**Comment by gorkem-bwl** [comment]
> @gorkem-bwl @parwatcodes
> 
> There are no UI changes in this PR as this is just a refactoring of the icons.

Got it, thanks!

**Comment by gorkem-bwl** [comment]
> > @SepidehShahbazi once you have a PR with a visual change, could you send images/videos supporting your work? This will also help me understand what has changed overall. Thanks!
> 
> @gorkem-bwl as @mahid797 has mentioned, in this case we don't have any UI changes. It's about refactoring Icons and converting them to React components instead of .svg, which triggers the icons to be reusable, flexible and easier for using, but during implementing this PR for other icons if there are some icons that are not match with the Figma icons and I change them, which causes the UI to be changed, I'll add photos/videos in the PR. Also, from now on when I create a PR, I can comment on the PR that we don't have any UI/visual changes here. And for those, which we have UI changes and I add some photos, I can mention you on those PRs about new or updated photos. I think it's easier for you to recognise new UI changes.

That's my bad. I mistakenly thought "refactoring" somehow meant new icons :-D Normally that doesn't happen. I'll be more careful next time.

**Pull request closed without merging**
