### PR TITLE
Feature/profile page

### PR DESCRIPTION
**Pull request by mahid797**
Issue #1 Profile Pages

Might require some changes when layout and sidebar are finalized. Haven't yet connected to backend.

### CODE REVIEW

**Comment by neerajsunil** [comment]
Hey @mahid797,

Some changes are required for the profile tab.

- the profile picture should not be a random image when the user does not have a profile picture, it should be an icon indicating this user has no profile picture, or an image indication this user has no profile picture
image
- the filler value should be something generic for empty fields, like "name@bluewave.com" or "name@email.com"
image

**Comment by gorkem-bwl** [comment]
For the default avatar, can we use the letter avatar where the letter is the user's first name? 

See: https://mui.com/material-ui/react-avatar/#letter-avatars

**Comment by mahid797** [comment]
> Hey @mahid797,
> 
> Some changes are required for the profile tab.
> * the filler value should be something generic for empty fields, like "[name@bluewave.com](mailto:name@bluewave.com)" or "[name@email.com](mailto:name@email.com)"
>   image

I thought our user accounts require an email for creation so the field will never be empty. I initially included the email as a placeholder rather than as a filler for an empty field.  It’s just there temporarily until the backend is up and running with some dummy data. Once that’s set, we can swap it out for the real data.

**Comment by mahid797** [comment]
> For the default avatar, can we use the letter avatar where the letter is the user's first name?
> 
> See: https://mui.com/material-ui/react-avatar/#letter-avatars

> Some changes are required for the profile tab.
> 
> * the profile picture should not be a random image when the user does not have a profile picture, it should be an icon indicating this user has no profile picture, or an image indication this user has no profile picture
>   image
> * the filler value should be something generic for empty fields, like "[name@bluewave.com](mailto:name@bluewave.com)" or "[name@email.com](mailto:name@email.com)"
>   image

@neerajsunil 
The empty profile picture will be the letter avatar, as @gorkem-bwl suggested. But as I don't have any names from backend I put lorem picsum as a place holder.

**Pull request merged**
