### PR TITLE
Refactor/register

### PR DESCRIPTION
**Pull request by SajanGhuman**
This PR improves over the previous PR with things like code refactoring(Addressing change requests from previous PR), code redundancy and adding email template for forgot password feature.  

Implemented:
- Reduce count of Prisma instances by initializing Prisma globally and making all files use that instance.
- Using only one UUID for generating tokens.
- New email template
email_template

- Email sending is now dynamic. (Note: Emails are only sent to authorized emails since it is still in testing. It will change as we move to production and have a public domain)
- More structured approach when returning errors.
- Delete app/api/send/route.ts as it was redundant and not needed.

### CODE REVIEW

**Comment by gorkem-bwl** [comment]
Looks good. We previously used MJML (https://mjml.io/) in two of our projects, so if you want to use that framework, that is fine. If not, that is fine as well.

**Comment by gorkem-bwl** [comment]
A few more tips:

- We can also change the "BlueWave Labs" wording to "BlueWave Dataroom". 
- There will be a documentation center on Gitbook, but I am not sure if we'd have "security tips" when we release 1.0
- We can use [DataRoom logo](https://www.figma.com/design/GLFfhwOQeHmbcflgCTuMKA/DataRoom-(Secure-File-Server)?node-id=68-2018&t=z3vMDyQgCRNv0TdB-1) that you can pick up from Figma, instead of the BlueWave Labs logo.

**Comment by SajanGhuman** [comment]
> Looks good. We previously used MJML (https://mjml.io/) in two of our projects, so if you want to use that framework, that is fine. If not, that is fine as well.

This looks cool. I will definitely have a in-depth look at this.

**Comment by SajanGhuman** [comment]
> A few more tips:
> 
>     * We can also change the "BlueWave Labs" wording to "BlueWave Dataroom".
> 
>     * There will be a documentation center on Gitbook, but I am not sure if we'd have "security tips" when we release 1.0
> 
>     * We can use [DataRoom logo](https://www.figma.com/design/GLFfhwOQeHmbcflgCTuMKA/DataRoom-(Secure-File-Server)?node-id=68-2018&t=z3vMDyQgCRNv0TdB-1) that you can pick up from Figma, instead of the BlueWave Labs logo.

My goal was to give a general idea of how the email template is going to look like. But as you mentioned, we will have to change a lot of thing before the finalization. And thanks for the logo, I needed that!

**Review by Paxxack — CHANGES_REQUESTED** [review]
Great PR! This will significantly enhance our current backend implementation.

**Comment by gorkem-bwl** [comment]
> My goal was to give a general idea of how the email template is going to look like. But as you mentioned, we will have to change a lot of thing before the finalization. And thanks for the logo, I needed that!

Yep, agreed! Thanks! :)

**Pull request merged**
